# Generated by Django 5.1.6 on 2025-08-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChatKnowledge",
            new_name="Chat",
        ),
    ]
