# Generated by Django 5.1.6 on 2025-08-02 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_chatsession_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_user",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                null="default",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default="default",
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(max_length=10, null="default"),
            preserve_default="default",
        ),
    ]
