# Generated by Django 5.1.6 on 2025-08-02 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_remove_message_is_user_chatsession_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                null="default",
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot.loginuser",
            ),
        ),
    ]
