# Generated by Django 5.1.6 on 2025-08-03 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_alter_chatsession_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="loginuser",
            name="created_at",
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                null="default",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chatbot.loginuser",
            ),
            preserve_default="default",
        ),
        migrations.AlterField(
            model_name="loginuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name="ChatSession",
        ),
    ]
