# Generated by Django 5.1.6 on 2025-08-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_delete_chat_remove_message_chat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(max_length=255, null="default"),
        ),
    ]
