# Generated by Django 5.1.6 on 2025-08-03 04:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0008_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="conversation_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
