# Generated by Django 5.1.6 on 2025-08-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0009_message_conversation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(default="user", max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chatbot.loginuser",
            ),
        ),
    ]
